[package]
name = "eg-preset-rs"
version = "0.1.0"
authors = ["Yruama_Lairba <yruama_lairba@hotmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
lv2-core = "2.*"
lv2-urid = "2.*"
urid = "0.1.*"
